"""Initial schema: 9 tables with pgvector

Revision ID: 311d23cd8df3
Revises:
Create Date: 2026-07-10 13:16:02.426907

"""

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "311d23cd8df3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("master_prompt", sa.Text(), nullable=False),
        sa.Column("tools", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("channels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("heartbeat_interval", sa.Integer(), nullable=False),
        sa.Column("llm_model", sa.String(length=100), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "concepts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("agent_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("difficulty", sa.Float(), nullable=False),
        sa.Column("embedding", Vector(dim=1536), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_concepts_agent_id"), "concepts", ["agent_id"], unique=False)
    op.create_table(
        "learners",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("agent_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("overall_mastery", sa.Float(), nullable=False),
        sa.Column("preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_active", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "concept_edges",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.String(length=64), nullable=False),
        sa.Column("edge_type", sa.String(length=50), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["concepts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["concepts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_concept_edges_source_id"), "concept_edges", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_concept_edges_target_id"), "concept_edges", ["target_id"], unique=False
    )
    op.create_table(
        "error_patterns",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("learner_id", sa.String(length=64), nullable=False),
        sa.Column("concept_id", sa.String(length=64), nullable=False),
        sa.Column("error_type", sa.String(length=100), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("examples", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_error_patterns_concept_id"), "error_patterns", ["concept_id"], unique=False
    )
    op.create_index(
        op.f("ix_error_patterns_learner_id"), "error_patterns", ["learner_id"], unique=False
    )
    op.create_table(
        "interactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("learner_id", sa.String(length=64), nullable=False),
        sa.Column("agent_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("user_input", sa.Text(), nullable=False),
        sa.Column("agent_response", sa.Text(), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=True),
        sa.Column("concept_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("corrections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mastery_deltas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tool_calls", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_interactions_agent_id"), "interactions", ["agent_id"], unique=False)
    op.create_index(
        op.f("ix_interactions_learner_id"), "interactions", ["learner_id"], unique=False
    )
    op.create_index(
        op.f("ix_interactions_session_id"), "interactions", ["session_id"], unique=False
    )
    op.create_table(
        "mastery",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("learner_id", sa.String(length=64), nullable=False),
        sa.Column("concept_id", sa.String(length=64), nullable=False),
        sa.Column("p_mastery", sa.Float(), nullable=False),
        sa.Column("p_transit", sa.Float(), nullable=False),
        sa.Column("p_slip", sa.Float(), nullable=False),
        sa.Column("p_guess", sa.Float(), nullable=False),
        sa.Column("interactions_count", sa.Integer(), nullable=False),
        sa.Column("correct_count", sa.Integer(), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mastery_concept_id"), "mastery", ["concept_id"], unique=False)
    op.create_index(op.f("ix_mastery_learner_id"), "mastery", ["learner_id"], unique=False)
    op.create_table(
        "outbound_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_id", sa.String(length=64), nullable=False),
        sa.Column("learner_id", sa.String(length=64), nullable=True),
        sa.Column("channel", sa.String(length=50), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sent", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outbound_messages_agent_id"), "outbound_messages", ["agent_id"], unique=False
    )
    op.create_table(
        "review_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("learner_id", sa.String(length=64), nullable=False),
        sa.Column("concept_id", sa.String(length=64), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("stability", sa.Float(), nullable=False),
        sa.Column("difficulty", sa.Float(), nullable=False),
        sa.Column("elapsed_days", sa.Float(), nullable=False),
        sa.Column("scheduled_days", sa.Float(), nullable=False),
        sa.Column("reps", sa.Integer(), nullable=False),
        sa.Column("lapses", sa.Integer(), nullable=False),
        sa.Column("state", sa.Integer(), nullable=False),
        sa.Column("last_review", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_review", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_items_concept_id"), "review_items", ["concept_id"], unique=False
    )
    op.create_index(
        op.f("ix_review_items_learner_id"), "review_items", ["learner_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_items_learner_id"), table_name="review_items")
    op.drop_index(op.f("ix_review_items_concept_id"), table_name="review_items")
    op.drop_table("review_items")
    op.drop_index(op.f("ix_outbound_messages_agent_id"), table_name="outbound_messages")
    op.drop_table("outbound_messages")
    op.drop_index(op.f("ix_mastery_learner_id"), table_name="mastery")
    op.drop_index(op.f("ix_mastery_concept_id"), table_name="mastery")
    op.drop_table("mastery")
    op.drop_index(op.f("ix_interactions_session_id"), table_name="interactions")
    op.drop_index(op.f("ix_interactions_learner_id"), table_name="interactions")
    op.drop_index(op.f("ix_interactions_agent_id"), table_name="interactions")
    op.drop_table("interactions")
    op.drop_index(op.f("ix_error_patterns_learner_id"), table_name="error_patterns")
    op.drop_index(op.f("ix_error_patterns_concept_id"), table_name="error_patterns")
    op.drop_table("error_patterns")
    op.drop_index(op.f("ix_concept_edges_target_id"), table_name="concept_edges")
    op.drop_index(op.f("ix_concept_edges_source_id"), table_name="concept_edges")
    op.drop_table("concept_edges")
    op.drop_table("learners")
    op.drop_index(op.f("ix_concepts_agent_id"), table_name="concepts")
    op.drop_table("concepts")
    op.drop_table("agents")
    # ### end Alembic commands ###
